def handle_exception(err: Exception):
    print(f"exception ({type(err)}) occurred: {err}")
